# Books table
booksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: "BookId"
        AttributeType: "S"
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: "BookId"
        KeyType: "HASH"
    Tags:
      - Key: Name
        Value: booksTable-${self:provider.stage}

# Orders table
ordersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: "UserId"
        AttributeType: "S"
      - AttributeName: "OrderId"
        AttributeType: "S"
      - AttributeName: "CreatedAt"
        AttributeType: "S"
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: "UserId"
        KeyType: "HASH"
      - AttributeName: "CreatedAt"
        KeyType: "RANGE"
    GlobalSecondaryIndexes:
      - IndexName: "byOrderId"
        KeySchema:
          - AttributeName: "OrderId"
            KeyType: "HASH"
        Projection:
          ProjectionType: ALL
    Tags:
      - Key: Name
        Value: ordersTable-${self:provider.stage}

# Cognito user pool
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: "BookStoreUserPool-${self:provider.stage}"
    UsernameAttributes:
      - email
    Schema:
      - AttributeDataType: String
        Mutable: true
        Name: name
        Required: false

# Cognito user pool client
cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: Web
    UserPoolId: !Ref cognitoUserPool

# Cognito Admin group
cognitoAdminGroup:
  Type: AWS::Cognito::UserPoolGroup
  Properties:
    Description: "Admin users of the bookstore"
    GroupName: "Admin"
    RoleArn: !GetAtt cognitoAdminGroupIAMRole.Arn
    Precedence: 0
    UserPoolId: !Ref cognitoUserPool

# Cognito Customer group
cognitoCustomerGroup:
  Type: AWS::Cognito::UserPoolGroup
  Properties:
    Description: "Customers of the bookstore"
    GroupName: "Customer"
    RoleArn: !GetAtt cognitoCustomerGroupIAMRole.Arn
    Precedence: 1
    UserPoolId: !Ref cognitoUserPool

# Cognito Admin group IAM role
cognitoAdminGroupIAMRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: "bookstore-admin-group-role"
    Description: "IAM role that admin group users assume in the bookstore application"
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Federated:
              - "cognito-identity.amazonaws.com"
          Action:
            - "sts:AssumeRoleWithWebIdentity"
    Policies:
      - PolicyName: "bookstore-admin-group-policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:*"
              Resource:
                - !GetAtt booksTable.Arn
                - !GetAtt ordersTable.Arn

# Cognit User group IAM role
cognitoCustomerGroupIAMRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: "bookstore-customer-group-role"
    Description: "IAM role that customer group users assume in the bookstore application"
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Federated:
              - "cognito-identity.amazonaws.com"
          Action:
            - "sts:AssumeRoleWithWebIdentity"
    Policies:
      - PolicyName: "bookstore-customer-group-policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            # Read only access to books table
            - Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:BatchGetItem"
                - "dynamodb:Query"
              Resource:
                - !GetAtt booksTable.Arn
            # Full access to OWN records in the order table
            - Effect: Allow
              Action:
                - "dynamodb:*"
              Resource:
                - !GetAtt ordersTable.Arn
              Condition:
                ForAllValues:StringEquals:
                  dynamodb:LeadingKeys: # "${cognito-identity.amazonaws.com:sub}" DOES NOT work as it conflicts with serverless variable reference '$'
                    - !Join ["", ["$", "{cognito-identity.amazonaws.com:sub}"]]