service: serverless-bookstore
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-2

package:
  exclude:
    - package.json
    - README.md

# Cloudformation resources
resources:
  Resources:
    ${file(resources.yml)}
  Outputs:
    BooksTable:
      Description: "Arn of the books table"
      Value: !GetAtt booksTable.Arn
    OrdersTable:
      Description: "Arn of the orders table"
      Value: !GetAtt ordersTable.Arn
    UserPoolId:
      Description: "Cognito user pool id"
      Value: !Ref cognitoUserPool